### PR TITLE
update gradle version for all the project iterations

### PR DESCRIPTION
**Pull request by thepri10**
Update gradle version for all the project iterations

### CODE REVIEW

**Comment by lacasseio** [comment]
This is a great PR. However, we are trying to get to a point that we can validate the samples is working for all Gradle version, not just the last one. I feel like some Gradle cross-version test would be in effect here. Do you want to help on that instead?

**Comment by thepri10** [comment]
That makes sense. When I saw that the build had failed, I could not understand why it would do so. About the cross-version Gradle testing, how would one go about that?

**Comment by lacasseio** [comment]
Hmmm, I see now. The guide is in a pretty bad shape in term of testing and ensuring it keeps working with all Gradle versions. The guide should be more clear on the Gradle distribution installation is needs, something like `A https://gradle.org/install[Gradle distribution], version {gradle-version} or better` in the required section and the wrapper should be removed from the samples. Let's action on this.

As for testing, let's ignore that one for now as we need to consider all guides and we are just starting with this process.

**Comment by lacasseio** [comment]
Also, don't forget to sign off on the commit of your next PR, see DCO bot details.

**Comment by lacasseio** [comment]
We will revisit this later.

**Pull request closed without merging**
